# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = opaque, class:^(zen)$
windowrule = float, title:^(pavucontrol)$
windowrule = float, title:^(blueman-manager)$
windowrule = float, title:^(nm-connection-editor)$
windowrule = float, title:^(qalculate-gtk)$

windowrule = workspace 2 silent, title:^(Picture-in-Picture)$

# idleinhibit
windowrule = idleinhibit fullscreen,class:([window]) # Available modes: none, always, focus, fullscreen

windowrule = workspace special:spotify, class:^(Spotify)$
windowrule = workspace special:messanger, class:^(Caprine)$
