# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = opaque, class:^(zen)$
windowrule = float, title:^(pavucontrol)$
windowrule = float, title:^(blueman-manager)$
windowrule = float, title:^(nm-connection-editor)$
windowrule = float, title:^(qalculate-gtk)$

windowrule = monitor 1, title:^(Picture-in-Picture)$

# idleinhibit
windowrule = idleinhibit fullscreen,class:([window]) # Available modes: none, always, focus, fullscreen

windowrule = workspace name:Spotify silent, class:^(Spotify)$
