# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule {
  name = opaque_browser
  opaque = on
  match:class = ^(zen)$
}

windowrule {
  name = floating_volume_control
  float = on
  match:title = ^(pavucontrol)$
}


windowrule {
  name = windowrule-6
  workspace = special:spotify silent
  match:class = ^(Spotify)$
}

windowrule {
  name = windowrule-7
  workspace = special:messanger silent
  match:class = ^(ferdium)$
}

windowrule {
  name = windowrule-8
  workspace = name:social silent
  match:class = ^(discord)$
}

windowrule {
  name = windowrule-9
  workspace = name:social silent
  match:class = ^(steam)$
}

windowrule {
  name = windowrule-10
  workspace = name:Gaming silent
  match:class = ^(steam_app_.*)$
}


# smart gaps
workspace = w[tv1]s[false], gapsout:0, gapsin:0
workspace = f[1]s[false], gapsout:0, gapsin:0
windowrule = border_size 0, rounding 0, match:float 0, match:workspace w[tv1]s[false]
windowrule = border_size 0, rounding 0, match:float 0, match:workspace f[1]s[false]


