# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------

# Default Settings in ml4w.conf
env = ELECTRON_OZONE_PLATFORM_HINT,discord
