# -----------------------------------------------------
# Monitor Setup
# name: "2560x1440@120"
# -----------------------------------------------------

monitor=DP-1,3840x1600@144.02,0x0,1
monitor=HDMI-A-1,1920x720,980x1600,1
